// <auto-generated />
namespace HierarchicalData.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddURL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddURL));
        
        string IMigrationMetadata.Id
        {
            get { return "201805281659111_AddURL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
